### PR TITLE
Remove custom HTTP error classes

### PR DESCRIPTION
**Pull request by JordanGuinn**
## Background
This PR removes the hand-rolled HTTP error classes we've written with their most robust equivalents outlined in https://github.com/jshttp/http-errors.

## GitHub Issue
N/A

## Associated PRs
N/A

## Validation Plan
- [x] Confirm application still builds and deploys without issue
- [x] Confirm 4XX HTTP errors can still be thrown by the application without issue
- [x] Confirm 5XX HTTP errors can still be thrown by the application without issue

## Automated Testing
- [x] All unit tests are passing.

### CODE REVIEW

**Review by bamader — APPROVED** [review]
Code looks fine here, but what's the impetus for the PR? Were our old errors just not handling things that we wanted covered, or is it just about paring down hand-rolled code?

**Comment by JordanGuinn** [comment]
@bamader Exactly that second part!  It's been on my radar for a while, and so a few days ago I just bit the bullet and put up a PR for it.  Though as part of the find/replace work here, it did reveal that we were improperly conflating both `Unauthorized` and `Forbidden` errors - really just more evidence that there's no need for us to reinvent the wheel here.

**Comment by bamader** [comment]
Gotcha. Seems like those http errors we're inheriting have the exact same signature and footprint as our old hand spun stuff so (without too much naive optimism lol) there probably shouldn't be any difficulties or complications replacing them.

_Because code always does exactly and only what you to tell it too_ 😅

**Review by jessethach — APPROVED** [review]
Looks good!

**Comment by bamader** [comment]
## Validation Plan
- [ ] Change enrollment page throws NotFound and BadRequest
- [ ] Create child throws BadRequest
- [ ] Delete record throws NotFound
   - Looks like we've grouped together two different types of errors into one response here. Comments on line 26 indicate that a NotFound is thrown if `child does not exist, or user does not have permission to modify`. The NotFound would for sure apply to the former case, but if we're re-tooling our HTTP errors, should we actually separate those out into a NotFound for the former and a Forbidden or BadRequest for the latter?
- [ ] Update record throws NotFound (also same thing as with delete)
- [ ] MapRows throws relevant HTTP Errors
- [ ] Lookup organization throws BadRequest
- [ ] Parse throws BadRequest
- [ ] Enrollment controller throws BadRequest and NotFound
- [ ] Income Determination throws NotFound
- [ ] OEC Report throws BadRequest
- [ ] Create org page throws Conflict
- [ ] user controller throws NotFound
- [ ] authentication middleware throws Unauthorized
- [ ] children route throws NotFound and BadRequest
- [ ] EnrollmentReport file upload controller throws BadRequest
- [ ] Enrollment route throws BadRequest
- [ ] Export route throws InternalServerError
- [ ] Families route throws BadRequest and NotFound
- [ ] Organizations route (admin) throws Forbidden and InternalServerError
- [ ] Revisions route throws BadRequest
- [ ] Summary route throws Forbidden
- [ ] Template route throws InternalServerError
- [ ] Users route throws Forbidden and BadRequest

**Comment by bamader** [comment]
Validations are good here. Once we've got tickets for the unrelated stuff I found this can be merged.

**Pull request merged**
