### PR TITLE
Fix date issue on roster redesign 

### PR DESCRIPTION
**Pull request by nickbristow**
## Background
Add date fix to roster redesign
## GitHub Issue
Replace this text with the GitHub issue link.

## Associated PRs
If applicable, replace this text with links to additional pull requests associated with this work.

## Validation Plan
Please outline the steps you've already taken to validate this body of work, along with any additional steps that need to be taken in order to complete testing.

## Tech Specs
- [ ] If any TypeORM entities were created/updated/removed, the necessary migration(s) were [correctly auto-generated](https://github.com/typeorm/typeorm/blob/master/docs/using-cli.md#generate-a-migration-from-existing-table-schema) and **not manually written**.

## Automated Testing
- [ ] All unit tests are passing.
- [ ] Unit tests have been added to cover this changeset.

## Additional Context
If there's any additional information that those reviewing or validating this work should be aware of, please specify it here.

### CODE REVIEW

**Review by lukenewman — APPROVED** [review]

**Review by gordonfarrell — APPROVED** [review]
Approving, starting validation in a minute

**Comment by gordonfarrell** [comment]
Validation

- [ ] Dates save and update correctly without shifting one day
- [ ] Upload of duplicate data is correctly ignored
- [ ] Same file reupload does not cause 500s

**Comment by lukenewman** [comment]
@gordonfarrell i'm seeing that validation point 2 is not correct. i'm uploading a roster with one child and after uploading it again, it says the child is a new record

**Comment by gordonfarrell** [comment]
Huh ok lemme go look again

**Comment by nickbristow** [comment]
@lukenewman @gordonfarrell we should note that this pr wasn't intended to fix those, but we were hoping it would.

**Comment by gordonfarrell** [comment]
Yeah sorry looks like I goofed that one you're right Luke. At least the date bit works perfectly!

**Pull request merged**
