### PR TITLE
Update query to include users without site or org permissions

### PR DESCRIPTION
**Pull request by nickbristow**
## Background
Get users query would not return a user who didn't have a full org permission or just site permission.

This update changes the getUser query to include all user regardless of org and site permissions.

## GitHub Issue
#1397 

## Validation Plan
- [ ] User with no org shows on admin user page
- [ ] User with only site permission shows on admin user page
- [ ] User with org permission shows on user page

## Automated Testing
- [ ] All unit tests are passing.

### CODE REVIEW

**Comment by nickbristow** [comment]
fyi: my vs code formatted the file i saved

**Review by vonbearshark — APPROVED** [review]
Seems 👍🏻  to me. And yeah idk what's up with the VSCode formatting. Same thing happened to me

**Review by JordanGuinn — APPROVED** [review]

**Comment by vonbearshark** [comment]
Looks like we need https://github.com/ctoec/data-collection/pull/1408 in for local tests

**Review by bamader — APPROVED** [review]

**Comment by bamader** [comment]
## Validation Plan
- [ ] User with no org shows on admin user page
- [ ] User with only site permission shows on admin user page
- [ ] User with org permission shows on user page

For non-admin users (necessary because the excel package is being updated here):
- [ ] Users can upload CSV files and .xlsx files correctly
  - [ ] Fully complete template
  - [ ] Template missing some information
  - [ ] Can't upload non-csv and non-xlsx files
  - [ ] Files with wrong column headers are flagged
- [ ] Users can export and download their roster

**Comment by JordanGuinn** [comment]
@bamader & I completed our validation passes without issue - this is ready for merge!

**Pull request merged**
