### PR TITLE
Delete "Review Missing Info" page from upload UX

### PR DESCRIPTION
**Pull request by lukenewman**
## Background
See title

## GitHub Issue
https://github.com/ctoec/data-collection/issues/1381

## Associated PRs
N/A

## Validation Plan
* [ ] upload a file and ensure the former middle (2nd) step is gone

## Tech Specs
N/A

## Automated Testing
- [ ] All unit tests are passing.
- [ ] Unit tests have been added to cover this changeset.

## Additional Context
N/A

### CODE REVIEW

**Review by GordonFarrell — APPROVED** [review]

**Review by bamader — APPROVED** [review]
As long as there aren't any associated API changes that need to be made, this looks good!

**Review by jessethach — APPROVED** [review]

**Comment by lukenewman** [comment]
@bamader i believe the upload errors still need to be passed to the client for (future) displaying on the upload confirmation screen

**Comment by JordanGuinn** [comment]
@lukenewman Can you point this PR at `EPIC-file-upload-UX-cleanup` instead of `base`?  We're gonna release this mini-epic of work all at once

**Comment by lukenewman** [comment]
big 🛑  on this one. need to re-create this work branched off of that epic and not base

**Comment by JordanGuinn** [comment]
For sure - sorry for not calling that out earlier 😕 I'll be sure to put the release branch names into the corresponding epics we have where that's applicable

**Comment by lukenewman** [comment]
@JordanGuinn all good! unfortunately the epic branch is not building tho :/

**Comment by lukenewman** [comment]
@JordanGuinn good to go

**Review by JordanGuinn — APPROVED** [review]

**Comment by bamader** [comment]
## Validation Plan

- [ ] Confirm user can reach the upload file wizard
- [ ] Confirm user can upload a correctly filled out file and persist changes to roster
- [ ] Confirm user can upload file that is in the correct format but missing information
- [ ] Confirm that app gracefully handles an uploaded template with wrong columns
- [ ] Confirm that app gracefully handles an upload that's the wrong kind of file

**Comment by bamader** [comment]
All validations passed. This is good to merge!

**Comment by GordonFarrell** [comment]
Anyone else getting this when they drop a file to upload? 
Screen Shot 2021-11-12 at 10 21 28 AM

You can click the X and continue on and it works fine. Says it may only appear in development but I figured I'd mention it. Also, I posted almost this exact comment on zenhub but then realized we do our chatting here, whoooops haha.

**Comment by lukenewman** [comment]
@GordonFarrell that is a known issue (only on local dev i believe)

**Review by JordanGuinn — APPROVED** [review]
LGTM!

**Pull request merged**
