### PR TITLE
Add e2e util for clearing db

### PR DESCRIPTION
**Pull request by bamader**
## Background
Provide a brief overview of the work completed here.

## GitHub Issue
Replace this text with the GitHub issue link.
**NOTE: Please don't mark the issue as closed by this pull request!  Issues are to be closed manually within Zenhub upon merge & prod deploy.**

## Associated PRs
If applicable, replace this text with links to additional pull requests associated with this work.

## Validation Plan
Please outline the steps you've already taken to validate this body of work, along with any additional steps that need to be taken in order to complete testing.

## Automated Testing
- [ ] All unit tests are passing.
- [ ] All e2e tests are passing.
- [ ] If applicable, unit tests have been added to cover this changeset.
- [ ] If applicable, e2e tests have been added to cover this changeset.

## Additional Context
If there's anything additional information that those reviewing or validating this work should be aware of, please specify it here.

### CODE REVIEW

**Comment by vonbearshark** [comment]
Is there a way to do this before like all tests? Some kind of global `beforeEach` or something?

**Comment by bamader** [comment]
I _think_ there is indeed some kind of `globalTest.js` thing you can write and run before every test, yeah. I don't know how to write one at present, but after I verify this against all the tests I can def look into the syntax for that. Would certainly simplify the number of places we have to call this, and then we're also future proofed for adding any other tests in the future.

**Comment by JordanGuinn** [comment]
Also, this will only ever work locally, as we don't spawn our DBs through Docker in any of our cloud environments.  Unfortunately, the fact that e2e tests were green here is assuredly a happy coincidence 😕

**Comment by bamader** [comment]
NOOOOOOOOOOOOO 😭 😭 😭 . I don't know if Nightwatch can directly invoke AWS commands either 😕

**Comment by JordanGuinn** [comment]
I don't know that there are any good AWS CLI commands to clear a DB of all data, so we'd likely have to bring in ol' Bobby Tables 😭 Cuz deleting and recreating an RDS instance takes **forever**.

Maybe this is still worth keeping around though, and just running when env is `local`?

**Comment by vonbearshark** [comment]
Wait we can run e2e tests locally? Doesn't browserstack require a deployed env?

**Comment by JordanGuinn** [comment]
Oh idk - I thought folks have been doing as much, but maybe they were actually just kicking them off locally, to be run on a deployed environment?

**Comment by bamader** [comment]
I also thought it required a deployed environment? Happy to keep this around, but very disappointed it doesn't actually apply to anything and deceived me with its flashiness and efficiency 😂 😭 . And yeah, looks like Nightwatch has no nice way to interface with AWS (not that it matters anyway).

**Comment by JordanGuinn** [comment]
Closing for now, until we can come up with a functional solution 😭

**Pull request closed without merging**
