### PR TITLE
489: Add validation for funded enrollment requirement

### LINKED ISSUE #489: No funding error state
**For records with no funding info (current or past):**

- Add validation in backend that ensures at least one enrollment has at least one funding, including past fundings
- Update error text to read "Add required info in [Section names] before submitting your data to OEC."
- add as validation

Screen Shot 2020-10-23 at 4 43 56 PM

### LINKED ISSUE #580: Child record missing info alert should show on opening a child record and persist until all errors are resolved.
- Red error Alert should display whenever a user opens a record with missing info
- The alert should persist as the user moves between sections
- The alert should remove section names as the user completes them
- The alert should disappear when the user adds all missing info
- Update second line of text to read: "Add required info in [Section names...].
Screen Shot 2020-10-14 at 2 39 10 PM

### PR DESCRIPTION
**Pull request by jlhogan**
put this on top of error boundary b/c it was easier so will make sure that gets merged first.

need eyes on how to do something with the missing funding alert, in absence of the funding card with missing info icons. threw placeholder error alert in there for now. 

closes #489 
closes #580

### CODE REVIEW

**Comment by RyanHansz** [comment]
Copy edits for the alert:
Header: This record is missing funding information
Text: Records must have at least one current or past state funding source to be submitted to OEC. Add funding info in the [enrollment and funding section](url).

**Comment by jlhogan** [comment]
@RyanHansz so nothing specifically within the ENrollment/Funding form, just an additional alert with the specific missing funded enrollment text. And that special alert is always visible, regardless of selected edit tab?

**Comment by RyanHansz** [comment]
> @RyanHansz so nothing specifically within the ENrollment/Funding form, just an additional alert with the specific missing funded enrollment text. And that special alert is always visible, regardless of selected edit tab?

@jlhogan yes. I'm assuming adding the missing icons to the funding section (image below) will come in a later ticket.
Screen Shot 2020-11-17 at 2 27 24 PM

**Review by bamader — APPROVED** [review]
LGTM! Was the solution of always displaying the special "must have a funded enrollment" alert what your comment was asking about?  Or we do still need to brainstorm something else to do with it?

**Review by mmazanec22 — APPROVED** [review]

**Review by JordanGuinn — APPROVED** [review]

**Pull request merged**
