### PR TITLE
Reorganize overview page contents

### PR DESCRIPTION
**Pull request by bamader**
## Background
This PR updates the design of the overview page available to admin OEC users.

## GitHub Issue
https://github.com/ctoec/data-collection/issues/1422

## Associated PRs
None

## Validation Plan
Log into app as admin user. Observe compliance with new designs.

## Automated Testing
- [ ] All unit tests are passing.
- [ ] If applicable, unit tests have been added to cover this changeset.

### CODE REVIEW

**Comment by JordanGuinn** [comment]
@bamader Looks good to me overall!  Just a couple minor tweaks to be made to match the designs.  Will include a screenshot:

- `Data status by site` above the tab nav needs to be removed
- Site count below the tab nav needs to be removed

Screen Shot 2021-08-30 at 11 20 23 PM

**Comment by bamader** [comment]
Validations addressed. Moving this over to ready!

**Comment by JordanGuinn** [comment]
## Validation Plan
- [ ] `In progress` wording has been updated to `Incomplete`
- [ ] `Overview` cards have been updated to match new designs
- [ ] Data dashboard alert has been added
- [ ] Tab nav is still functional
- [ ] Site table has been updated to match designs

**Comment by JordanGuinn** [comment]
Both minor design issues have been addressed - this is good to go!

**Pull request merged**
