### PR TITLE
Align TypeORM entities and db schema

### PR DESCRIPTION
**Pull request by JordanGuinn**
## Background
Today @jessethach uncovered a handful of TypeORM entity changes that were not properly reflected in the corresponding db schema (a very bad thing) - this PR addresses the majority of those changes.

- Fixes the `FundingReport` schema, as the db table and the corresponding TypeORM entity were substantially different
- Adds the `CreateDateColumn` annotation to all `createDate` columns, so that we have that field set automatically for all INSERTs
- Removes the `EnrollmentReport` entity and table, because we don't use that in any capacity at all anymore
- Auto-generated a handful of DB migrations based on the entity state after making the aforementioned changes, so that our database and our TypeORM entities actually kinda mirror each other 😬 
- Updates the PR template to include auto-generating migrations from TypeORM entities, so ideally we don't get too far into a situation like this again

## GitHub Issue
N/A

## Associated PRs
N/A

## Validation Plan
TBD

## Automated Testing
- [x] All unit tests are passing.

### CODE REVIEW

**Review by bamader — APPROVED** [review]

**Review by jessethach — APPROVED** [review]
Thank you! This will unblock me. Do you know if this issue broke prod in any way?

**Comment by JordanGuinn** [comment]
@jessethach I don't think so, thankfully - the discrepancies were primarily scoped to database tables that receive between minimal and zero use.

**Comment by jessethach** [comment]
I have validated this branch and it is running locally with no issues. Confirming the new migration files have been added:

Screen Shot 2021-11-03 at 10 24 22 AM

**Comment by bamader** [comment]
Can you post your validation plan / checks you ran to confirm that this integrates with existing functionality? Something like:

## Validation Plan
- [ ] Confirm migrations run and new versions of modified entities appear in the DB
- [ ] User can upload a spreadsheet using the new schemas
- [ ] etc.

That's especially important imo for a PR like this that modifies such a core piece of the app.

**Comment by jessethach** [comment]
As @bamader suggested in Slack, I did a more comprehensive QA. Looks like fetching children is returning 500s. 

Screen Shot 2021-11-03 at 11 21 31 AM

With error:

```
{"message":"TypeError: Cannot set property 'validationErrors' of null"}
```

**Comment by jessethach** [comment]
@bamader Missed your comment above. I referenced your Slack message in my previous post. Will make validation plan below.

## Validation Plan
- [ ] Confirm migrations run and new versions of modified entities appear in the DB
- [ ] Confirm that user can upload a spreadsheet using the new schemas
- [ ] Confirm successful fetch of roster data after importing from spreadsheet
- [ ] Confirm that roster data can be added manually (e.g. insert without csv)

**Review by lukenewman — APPROVED** [review]

**Comment by JordanGuinn** [comment]
@bamader @jessethach Figured out what the issue was - turns out that my attempt to properly configure the relationship between `Child` and `Family` entities _actually_ caused our validation mechanism to break, as it expects `familyId` to be present, not just the `family` 🤦 😭 

Because that logic is super gross and complicated, I decided to just revert my changes to the `Child` entity, as we don't really need them here I suppose.  Either way, this is ready for another validation pass.

**Comment by bamader** [comment]
@JordanGuinn Excellent! Gonna get on this right after lunch.

**Comment by bamader** [comment]
## Validation Plan
- [ ] Confirm migrations run and entities with appropriate properties are created
- [ ] AddSiteRequest correctly created with revisions page
- [ ] ChangeFundingRequest correctly created with revisions page
- [ ] UpdateSiteRequest correctly created with revisions page

**Comment by bamader** [comment]
_WOW_ so apparently the build error I thought this PR was giving me was _actually_ just my own local docker issue 🤦 . Love it when a simple validation takes twice as long as it should 🙃 . But, in any case, this is good to go because it actually works (unlike my computer today lol).

**Pull request merged**
