### PR TITLE
Roster list view columns overlap each other if too long

### PR DESCRIPTION
**Pull request by lukenewman**
## Background
See bug ticket. This just removes the `no-wrap` class from the name `Link`.

## GitHub Issue
https://github.com/ctoec/data-collection/issues/1571

## Associated PRs
N/A

## Validation Plan
- [ ] edit a child's name so that it's really really really really really really really really long
- [ ] ensure the really really really really really really really really long name wraps to the next line rather than overflowing

## Tech Specs
- [ ] If any TypeORM entities were created/updated/removed, the necessary migration(s) were [correctly auto-generated](https://github.com/typeorm/typeorm/blob/master/docs/using-cli.md#generate-a-migration-from-existing-table-schema) and **not manually written**.

## Automated Testing
- [ ] All unit tests are passing.
- [ ] Unit tests have been added to cover this changeset.

## Additional Context
If there's any additional information that those reviewing or validating this work should be aware of, please specify it here.

### CODE REVIEW

**Review by gordonfarrell — APPROVED** [review]
Looks good to me!

**Comment by jessethach** [comment]
I can validate this PR.

**Comment by jessethach** [comment]
- [ ] edit a child's name so that it's really really really really really really really really long
- [ ] ensure the really really really really really really really really long name wraps to the next line rather than overflowing


Screen Shot 2021-12-13 at 9 05 56 AM

@lukenewman Looks like removing the class did not solve for this use case (macOS Big Sur, Chrome).

**Comment by lukenewman** [comment]
@jessethach this should be good for another validation pass

**Comment by jessethach** [comment]
- [ ] edit a child's name so that it's really really really really really really really really long
- [ ] ensure the really really really really really really really really long name wraps to the next line rather than overflowing


Screen Shot 2021-12-15 at 9 26 25 AM

Passed!

**Pull request merged**
