### PR TITLE
Merge base into EPIC-file-upload-UX-cleanup

### PR DESCRIPTION
**Pull request by lukenewman**
## Background
Merged base

## GitHub Issue
https://github.com/ctoec/data-collection/issues/1592

## Associated PRs
~[This component library PR needs to be reviewed and merged first.](https://github.com/ctoec/component-library/pull/184)~

## Validation Plan
Validate file upload still works

## Tech Specs
- [ ] If any TypeORM entities were created/updated/removed, the necessary migration(s) were [correctly auto-generated](https://github.com/typeorm/typeorm/blob/master/docs/using-cli.md#generate-a-migration-from-existing-table-schema) and **not manually written**.

## Automated Testing
- [ ] All unit tests are passing.
- [ ] Unit tests have been added to cover this changeset.

## Additional Context
If there's any additional information that those reviewing or validating this work should be aware of, please specify it here.

### CODE REVIEW

**Review by jessethach — APPROVED** [review]

**Comment by jessethach** [comment]
@nickbristow @bamader I will take this on for validation.

**Comment by jessethach** [comment]
Validation plan:

- [ ] Validate file upload still works
- [ ] Login and general functionalities (i.e. navigating all pages) work

**Comment by jessethach** [comment]
@nickbristow @bamader @lukenewman This is validated and ready to go! Validation steps outlined above.

**Review by gordonfarrell — APPROVED** [review]
Looks bueno and validated by Jesse so this is good to merge

**Pull request merged**
