### PR TITLE
Fix admin users can specify negative capacity values 

### PR DESCRIPTION
**Pull request by jessethach**
## Background
- Add minimum value to disallow negative numbers in input.

## GitHub Issue
#1569

## Associated PRs
None

## Validation Plan

**Login as Admin**
- [ ] Navigate to Organization page and enter negative value. Confirm that the field does not allow negative values and will throw up error if submitted.

## Tech Specs
N/A

## Automated Testing
- [ ] All unit tests are passing.
- [ ] Unit tests have been added to cover this changeset.

## Additional Context
N/A

  https://user-images.githubusercontent.com/10701395/146615627-a7e512fe-e7cf-447b-a0dc-911a8b8d87f8.mov

### CODE REVIEW

**Review by nickbristow — APPROVED** [review]

**Review by lukenewman — APPROVED** [review]
nice

**Review by bamader — APPROVED** [review]
best kind of PR there is

**Comment by bamader** [comment]
## Validation Plan
Log into app as admin, navigate to edit org page for an organization.

- [ ] can edit and save positive/zero capacities without issue
- [ ] cannot save with a negative number entered in a capacity field
   - This test is _technically_ passing, but not in a way that I think matches expected or desirable behavior. If a user types in a negative number, a red stop sign warning label is displayed in the field. However, once a user clicks out of the field (either somewhere else on the page or another button), the value is changed to a 0 and the warning disappears. This means that the field is now valid again and so can be saved. If a user is moving quickly through the page, I think this change is subtle enough so as to not be detected (happened to me first time, actually). A better approach would be to highlight the field red (or leave the warning sign in there if a negative number is entered), but then deliberately _don't_ change the value to 0 when a user clicks away. If a save attempt is made while one or more fields is negative, we block the request from sending and instead show a banner `alert` at the top of the page indicating that one or more sites has a negative capacity, which is prohibited.

**Comment by jessethach** [comment]
@bamader I will work on displaying the validation message you mentioned. I may need to strip that min prop if that's the case because I think there is some default Carbon behavior with min/max values. I'll keep you posted.

**Comment by jessethach** [comment]
@bamader Changed the logic so that the `-` character is restricted on key press. Let me know if you agree with this pattern. I did not personally find it too invasive as a user. Others may feel different!

**Comment by bamader** [comment]
@jessethach Yeah I don't think I find this too intrusive. My only suggestion would be to change the copy that comes up with a blank capacity field to "Non-negative capacity number is required" instead of "Valid capacity...". That way we emphasize/explain why the '-' key is disabled.

**Comment by jessethach** [comment]
@bamader Copy is changed! Thanks for looking it over.

**Comment by gordonfarrell** [comment]
Ran this through validation, I like the total inability to even put in a - . Nice! That's working as intended, good fix for this.

Only small issue I'm seeing is that on clicking to add a new funding space when the space pops up its already showing a validation error requiring the capacity before a user even touches the field. Assuming we want to default to no error until submission?
Screen Shot 2022-01-04 at 2 46 42 PM

Other than that looks great! 👍

**Comment by jessethach** [comment]
@gordonfarrell Good catch! I will look into possibly defaulting the value to `0` or allowing it to be empty, at least until submission.

**Review by gordonfarrell — APPROVED** [review]

**Pull request merged**
