### PR TITLE
Remove user permissions from org UIs 1543

### PR DESCRIPTION
**Pull request by gordonfarrell**
## Background
Removed ability to assign permissions for users from the Org Create/Edit page.  Also removed related logic from the backend.

## GitHub Issue
https://github.com/ctoec/data-collection/issues/1543

## Associated PRs
N/A

## Validation Plan
Tested that org creation and updating still works properly

## Tech Specs
- [ ] If any TypeORM entities were created/updated/removed, the necessary migration(s) were [correctly auto-generated](https://github.com/typeorm/typeorm/blob/master/docs/using-cli.md#generate-a-migration-from-existing-table-schema) and **not manually written**.

## Automated Testing
- [X] All unit tests are passing.
- [ ] Unit tests have been added to cover this changeset.

## Additional Context
N/A

### CODE REVIEW

**Review by lukenewman — APPROVED** [review]
lgtm! be sure to check out the unused import/var alerts

**Review by jessethach — APPROVED** [review]
Sweet deletions!

**Review by JordanGuinn — APPROVED** [review]

**Review by bamader — APPROVED** [review]
LGTM. Validating now.

**Comment by bamader** [comment]
## Validation Plan
From the admin view:
- [ ] Create org page has no section for user permissions
- [ ] User can still create orgs without issue
- [ ] Edit org page has no section for user permissions
- [ ] User can still edit orgs without issue
- [ ] Create and edit user pages still show permissions section
- [ ] Can give a user permissions at creation
- [ ] Can add permissions to a user during editing
- [ ] Can remove permissions from a user during editing

**Comment by bamader** [comment]
Unrelated to validations but org search is working perfectly fine in this PR. (Well, I guess kind of related to validations because I had to explicitly use org search here, but it works).

**Comment by bamader** [comment]
This PR is good to go!

**Pull request merged**
