### PR TITLE
Use our own custom images in CircleCI deploys

### PR DESCRIPTION
**Pull request by JordanGuinn**
Necessary because Docker is gonna start rate limiting image pulls, and we don't want to drastically reduce our CI/CD capacity.

**Associated PR:** https://github.com/skylight-hq/ctoec-devops/pull/133

### CODE REVIEW

**Review by bamader — APPROVED** [review]

**Review by mmazanec22 — APPROVED** [review]

**Comment by mmazanec22** [comment]
Approved with a q: how do we make sure that the images are kept up to date?  Is there a way we can nudge developers to go update them if they're old?

**Comment by JordanGuinn** [comment]
I'd imagine we could set up a CloudWatch notification or something to regularly bug devs, or if we wanted to get REALLY autonomous, set up a pipeline on a regular schedule that continually pushed updated images.  Or just put a note about it in the to-be-created wiki 😅

**Comment by mmazanec22** [comment]
Lol @JordanGuinn I was thinking more like something that console logs the age of the image somehow when you docker up or down on the command line... really whatever makes sense is fine, idk best practices in this area and was mostly just curious

**Comment by JordanGuinn** [comment]
Gotcha.  Right now this only replaces the images used within CircleCI builds and deploys - local dev still pulls directly from the Docker registry.  That's an interesting idea though; maybe we _do_  just use the same image everywhere, for the sake of consistency 🤔 I'll make a follow-up ticket with all these options

**Review by jlhogan — APPROVED** [review]

**Pull request merged**
