### PR TITLE
Vonbearshark/1280 retry

### PR DESCRIPTION
**Pull request by vonbearshark**
## Background
- Created an Edit org flow, including UI and backend
- Abstracted out the existing Create code to be leveraged by both Create and Edit
- Made Title I and Region optional fields on sites
- Reorganized the /organizations route

## GitHub Issue
#1280 

## Validation Plan
 Validation plan for Create and Edit flow (extended from older PRs)
 
 - [x] Organizations are created successfully when name is available
    - [x] Success messaging indicates as much
- [x] Organizations are NOT created successfully when name is unavailable
    - [x] Error messaging indicates as much
 - [x] Organizations are edited successfully
    - [x] Success messaging indicates as much
- [x] Create an organization with one site without issue
   - [x] Confirm age group can be saved successfully
   - [x] Confirm success banner is displayed
   - [x] Confirm user is navigated back to the main admin view
- [x] Edit an organization with one site without issue
   - [x] Confirm age group can be saved successfully
   - [x] Confirm success banner is displayed
   - [x] Confirm properties like Registry ID is both required and set
- [x] Create an organization with multiple sites without issue
   - [x] Confirm success banner is displayed
   - [x] Confirm user is navigated back to the main admin view
- [x] Edit an organization with multiple sites without issue
   - [x] Confirm success banner is displayed
- [x] Confirm an org with one site **isn't** created under the following conditions:
   - [x] Site name is missing
   - [x] Registry ID is missing
   - [x] There is a CDC funding and Title I is missing
   - [x] There is a CDC funding and Region is missing
- [x] Confirm an org with one site **isn't** edited under the following conditions:
   - [x] Site name is missing
   - [x] Registry ID is missing
   - [x] There is a CDC funding and Title I is missing
   - [x] There is a CDC funding and Region is missing
- [x] Confirm an org with multiple sites **isn't** created under the following conditions:
   - [x] Site name is missing for one site
   - [x] Registry ID is missing for one site
   - [x] There is a CDC funding and Title I is missing for one site
   - [x] There is a CDC funding and Region is missing for one site
   - [x] Two sites share the same name
- [x] Confirm an org with multiple site **isn't** edited under the following conditions:
   - [x] Site name is missing for one site
   - [x] Registry ID is missing for one site
   - [x] There is a CDC funding and Title I is missing for one site
   - [x] There is a CDC funding and Region is missing for one site
   - [x] Two sites share the same name
- [x] Confirm a user can remove sites they inadvertently added during org creation
- [x] Confirm a user can remove sites they inadvertently added during org editing
- [x] Confirm adding a site, then removing it, then saving the org does not include that removed site
- [x] Confirm users can be assigned to orgs
- [x] Confirm users can be assigned to sites
- [x] Confirm users can be unassigned to orgs
- [x] Confirm users can be unassigned to sites
- [x] Confirm users can be added to multiple organizations from the `Edit User` page
- [x] Confirm users can be added to multiple organizations from the `Edit Organization` page
- [x] Confirm users can be added to sites at multiple organizations from the `Edit User` page
- [x] Confirm users can be added to sites at multiple organizations from the `Edit Organization` page
- [x] Confirm org search on the `Edit User` page still works

--- 

Completed, and should not need to be re-validated based on iteration:

Validation plan for Overview/Summary changes
- [x] Confirm counts of:
    - [x] Organizations
    - [x] Sites
    - [x] Enrollments
    - [x] Users

## Automated Testing
- [x] All unit tests are passing.

~- [ ] If applicable, unit tests have been added to cover this changeset.~

## Additional Context
I tried to group related changes to be reviewed commit-by-commit, if that's helpful

Previous PR here https://github.com/ctoec/data-collection/pull/1477

### CODE REVIEW

**Comment by vonbearshark** [comment]
re: the most recent validation:

On prod/couldn't repro (probably fixed with other changes)/unrelated:

- Success messaging indicates as much Message is displayed and then page refreshes immediately
- Getting an error when trying to access users orgs (User > user name)
- Deleting the registry ID allows you to create the org
- Empty sites in Site Permissions field for user (unnamed 1x in UI)
- Able to edit an org and give sites the same name

**Comment by bamader** [comment]
Documenting here cuz I think it's weird, but if you try to submit an org without specifying a site's registry ID, you get error messaging asking you to provide _invalid_  text, like so:
Screen Shot 2021-09-29 at 3 50 13 PM

If this is copy we can control, we should fix that to either say the entered value (or lack thereof) is invalid, or that the user needs to provide valid text. But I suspect it's a carbon default error message.

**Comment by bamader** [comment]
Also as a general comment, working through validations, I'd prefer the save button on the Edit Organization workflow to have different text. "Edit Organization" sounds to me like a button I need to hit before I'm able to make edits. I'd make a nit suggestion to change that copy to "Save Edits" or "Save changes to organization".

**Comment by JordanGuinn** [comment]
+1 for `Save changes` - that's what the designs show, anyway

**Comment by bamader** [comment]
Finished with validations. There seem to be a couple of types of issues, notably around
- The success banner alert and immediate page refreshing (for both single-site and multi-site org creation)
- CDC constraints on Title I and Region
- Registry ID saving
- Site permissions and features (i.e. names).

**Comment by vonbearshark** [comment]
- re: `Save changes` - agreed and ✅ 
- re: Registry ID erro - we _can_ control this and ✅ 

- re: success banner: as far as I can tell this exists in the existing create org flow, unless there is something I am missing? The way our alerts are managed in state it might be a little tough to address this fix, actually. And I wouldn't be surprised if we were having similar issues with alerts across the app. But if it's new and worthwhile I can definitely investigate further

**Comment by vonbearshark** [comment]
Fix ended up being trickier on the client than expected, but just pushed feedback fixes. Should be ready for re-review/validation

**Review by JordanGuinn — APPROVED** [review]

**Pull request merged**
