### PR TITLE
Add smart start recovery

### PR DESCRIPTION
**Pull request by nickbristow**
## Background
Adds smart start recovery funding source
## GitHub Issue
#1468 

## Associated PRs
N/A

## Validation Plan
Please outline the steps you've already taken to validate this body of work, along with any additional steps that need to be taken in order to complete testing.

## Automated Testing
- [x] All unit tests are passing.

### CODE REVIEW

**Review by vonbearshark — APPROVED** [review]

**Comment by JordanGuinn** [comment]
@nickbristow tests are failing

**Review by JordanGuinn — APPROVED** [review]
This is fine for the purposes of this ticket, but probably worth following up to re-envision how we associate corresponding upload values to their enum equivalents (cuz this is starting to feel more and more brittle).  Will create a ticket.

**Comment by JordanGuinn** [comment]
## Validation Plan
- [ ] OEC admins can create new funding spaces with the `SSR` funding source during org creation
- [ ] OEC admins can update existing funding spaces with the `SSR` funding source during org creation
- [ ] Enrollments with `SSR` are displayed appropriately in the roster
- [ ] Providers can upload files that include rows with the `SSR` funding source
- [ ] When creating a new child row, providers can specify `SSR` as a funding source for the current enrollment
- [ ] Providers can specify `SSR` as a funding source when changing an enrollment's funding
- [ ] Providers can specify `SSR` as a funding source when changing a child's enrollment

**Comment by JordanGuinn** [comment]
No issues found whatsoever - this is ready to merge!

**Pull request merged**
