### PR TITLE
[1078] Users want to enter negative family income values

### PR DESCRIPTION
**Pull request by lukenewman**
## Background
These changes allow income to be provided as a negative number and swap out the `TextInput` component for Carbon's `NumberInput`.

## GitHub Issue
https://github.com/ctoec/data-collection/issues/1078

## Validation Plan
- [ ] On both the create and edit record pages:
    - [ ] On the family income form step, enter a negative value and ensure that it doesn't autocorrect to a positive one
    - [ ] Save the form step without a value and ensure that the invalid state is triggered (red outline with ❗️ icon)
    - [ ] Save the form with a negative value and ensure that on the form step overview page the income value properly reflects the negative value

## Automated Testing
- [ ] All unit tests are passing.
- [ ] If applicable, unit tests have been added to cover this changeset.

## Additional Context
Please note that I was unable to verify if the custom style overriding actually works or not because my local dev environment decided to break in the final hours of my last day before PTO. Some additional work may be needed to get the label text to match the custom components'. See `index.scss` for class override.

### CODE REVIEW

**Review by JordanGuinn — APPROVED** [review]

**Review by bamader — APPROVED** [review]
LGTM!

**Comment by JordanGuinn** [comment]
## Validation Plan
### Creating a Child Row

### Editing a Child Row

**Comment by JordanGuinn** [comment]
I've uncovered a handful of issues during my validation pass here:

- When editing an existing income determination for an existing child record, the income field is shown in an error state, regardless of whether or not a valid value exists
- When creating a new child, if you complete the `Family Income` section successfully, get to the `Enrollment and Funding` section, then return to the `Family Income` section, you'll notice the income field is incorrectly shown to be in an error state
- When creating a new child, if you leave the `Annual household income` field blank, the `Family Income` section itself will correctly shown an error, but the income field will incorrectly appear to be fine

**Comment by bamader** [comment]
Just pushed up the fix for the issues you found, Jordan. I re-validated the tests and wasn't able to generate any of the errors you originally uncovered, but feel free to run through another validation suite of your own.

**Comment by JordanGuinn** [comment]
Just re-validated and confirmed that everything looks to be have been addressed!

The only issue that I found is something that _may_ exist independently of this work: when a user is creating a child record, after specifying the family income fields once, there's no way to go back and edit them successfully.  Like you can go back to that section of the form and change the fields, but once you press save they just revert back to their previous values.

Will validate with our current code to confirm it's an already existing bug, and if so, I'd say this is ready for merge (and will make a ticket for that).

**Comment by bamader** [comment]
@JordanGuinn Did you have a chance to check if that bug was already present in our code? Wanna move this bad boi to ready if it's soon-to-be merged.

**Comment by JordanGuinn** [comment]
Confirmed - this is an issue independent of this work.  With that, this is ready to merge.

**Pull request merged**
