### PR TITLE
Change logic from previous month to current month in api

### PR DESCRIPTION
**Pull request by jessethach**
## Background
- Add logic to backend summary to catch submission date condition between start and end of current month.

## GitHub Issue
https://github.com/ctoec/data-collection/issues/1490

## Validation Plan
- [ ] As **user** role, submit add sample data and submit roster for the month
- [ ] Navigate to Overview page as **admin** role
- [ ] Confirm as **admin** that submitted roster is shown as completed in Overview page

## Automated Testing
- [ ] All unit tests are passing.

Screen Shot 2021-10-27 at 9 12 13 AM
Screen Shot 2021-10-27 at 9 28 46 AM
Screen Shot 2021-10-27 at 9 58 04 AM

### CODE REVIEW

**Review by lukenewman — APPROVED** [review]

**Review by bamader — COMMENTED** [review]
Looks like this PR misses the first bullet of the AC (which is a copy update on what the results in the table cover). I think using current month instead of prevMonth should make sure the stats that are shown in the boxes are correct, though.

**Comment by jessethach** [comment]
@bamader Yes - that was covered in #1524 that I had preemptively merged into base. This PR moreso relates to the ticket rather than cover the whole ticket. Good catch though!

**Comment by JordanGuinn** [comment]
## Validation Plan
- [ ] Confirm the `Data collection status` header has been updated to indicate the request for the previous month

### No Complete Organizations
- [ ] Confirm the `Incomplete` sites card shows the proper count of all sites for which the organizations have **not** been marked as complete this month
- [ ] Confirm the sites in the corresponding `Incomplete` tab shows the correct sites
- [ ] Confirm the `Complete` sites card shows the proper count of all sites for which the organizations have been marked as complete this month
- [ ] Confirm the sites in the corresponding `Complete` tab shows the correct sites
- [ ] Confirm the `Complete` sites card shows the proper count of all sites for which the organizations have been marked as complete this month
- [ ] Confirm the sites in the corresponding `Complete` tab shows the correct sites
- [ ] Confirm the `No data` sites card shows the proper count of all sites for which the organizations have **not** been marked as complete this month, but also have no **active** enrollments
- [ ] Confirm the sites in the corresponding `No data` tab shows the correct sites

### Some Complete Organizations
- [ ] Confirm the `Incomplete` sites card shows the proper count of all sites for which the organizations have **not** been marked as complete this month
- [ ] Confirm the sites in the corresponding `Incomplete` tab shows the correct sites
- [ ] Confirm the `Complete` sites card shows the proper count of all sites for which the organizations have been marked as complete this month
- [ ] Confirm the sites in the corresponding `Complete` tab shows the correct sites
- [ ] Confirm the `No data` sites card shows the proper count of all sites for which the organizations have **not** been marked as complete this month, but also have no **active** enrollments
- [ ] Confirm the sites in the corresponding `No data` tab shows the correct sites

### All Complete Organizations
- [ ] Confirm the `Incomplete` sites card shows the proper count of all sites for which the organizations have **not** been marked as complete this month
- [ ] Confirm the sites in the corresponding `Incomplete` tab shows the correct sites
- [ ] Confirm the `Complete` sites card shows the proper count of all sites for which the organizations have been marked as complete this month
- [ ] Confirm the sites in the corresponding `Complete` tab shows the correct sites
- [ ] Confirm the `No data` sites card shows the proper count of all sites for which the organizations have **not** been marked as complete this month, but also have no **active** enrollments
- [ ] Confirm the sites in the corresponding `No data` tab shows the correct sites

**Comment by JordanGuinn** [comment]
Works like a charm!  I'd say this is ready for merge

**Pull request merged**
