### PR TITLE
Show past enrollments toggle

### PR DESCRIPTION
**Pull request by gordonfarrell**
## Background

Add a toggle to include past enrollments in the Roster Redesign roster view to preserve the ability for providers to see withdrawn students.

## GitHub Issue
[Ticket #1619](https://app.zenhub.com/workspaces/ece-dev-board-5ff506028d35f30012e0e937/issues/ctoec/data-collection/1619)

## Associated PRs
N/A

## Validation Plan
- [ ] Roster and toggle default to only current enrollments
- [ ] Toggling this feature updates the roster list automatically
- [ ] When toggle is on, shows current AND previous enrollments in the roster table
- [ ] Normal filters and sorting work as expected when combined with this toggle
- [ ] Other basic app functionality is unchanged

## Tech Specs
N/A

## Automated Testing
- [x] All unit tests are passing.

## Additional Context
N/A

### CODE REVIEW

**Review by lukenewman — APPROVED** [review]

**Review by SMakaiTakori — APPROVED** [review]
Looks great, nice work!

**Comment by jessethach** [comment]
I'll validation for this PR.

**Comment by jessethach** [comment]
Using the follow validation steps:

- [ ] Roster and toggle default to only current enrollments
- [ ] Toggling this feature updates the roster list automatically
- [ ] When toggle is on, shows current AND previous enrollments in the roster table
- [ ] Normal filters and sorting work as expected when combined with this toggle
- [ ] Other basic app functionality is unchanged

**Comment by jessethach** [comment]
@nickbristow @gordonfarrell This has been validated by @SMakaiTakori and I!

This is ready for merge.

**Pull request merged**
