### PR TITLE
Fix incorrect child record totals on roster page

### PR DESCRIPTION
**Pull request by JordanGuinn**
## Background
The total child record numbers on the roster page are currently tied to the last page the user has visited, and not the total number of records returned from the underlying query.  This PR addresses those inaccuracies.

## GitHub Issue
- https://github.com/ctoec/data-collection/issues/1012

## Associated PRs
N/A

## Validation Plan
- [x] All funding spaces are still available in funding space dropdown when changing child's enrollment
- [x] Roster count is accurate for a roster with **less than 100 children**
- [x] Roster data is correct for a roster with **less than 100 children**
- [x] Roster count is accurate for a roster with **greater than 100 children**, both
   - [x] **Before** loading the next page
   - [x] **After** loading the next page
- [x] Roster export operates and includes the same data as it did previously
- [ ] Roster count is accurate when applying the **previous month filter**
- [ ] Roster data is correct when applying the **previous month filter**
- [x] Child count is accurate on the batch edit page for children with missing info
- [x] Child data is correct on the batch edit page for children with missing info

## Automated Testing
- [x] All unit tests are passing.
- [ ] All e2e tests are passing.

### CODE REVIEW

**Review by jlhogan — APPROVED** [review]

**Review by bamader — APPROVED** [review]

**Comment by vonbearshark** [comment]
Checking in on the state of this. I might like to lift the pattern for the active/withdrawn validation errors count. Is this generally a working idea/PR, or a potential pitfall? Also, would you like a hand moving this along? I could even pick it up, code-wise, if there was something to be done still.

**Comment by JordanGuinn** [comment]
@vonbearshark It's a working idea, there's just one outstanding issue with roster counts when applying the `Previous month` filter being inaccurate and I just haven't had the time to address that last piece 😕

And now that I think about it, I imagine is inherently getting addressed in the previous month filter ticket you're working on 😅

**Comment by vonbearshark** [comment]
Ha. Yeah I think I can see how this fits together. I would be happy to just incorp these changes into my PR? Or push to this?

**Comment by JordanGuinn** [comment]
Perf - let's incorporate these changes into your PR then 🙂

**Comment by vonbearshark** [comment]
Closing out this PR, but stay tuned for the future ✨

**Pull request closed without merging**
