### PR TITLE
Fix Change Enrollment cancel button not closing modal

### PR DESCRIPTION
**Pull request by GordonFarrell**
## Background
This PR fixes a bug with the Change Enrollment modal where the cancel button would not close the modal on click

## GitHub Issue
[#1321 ](https://github.com/ctoec/data-collection/issues/1321)

## Validation Plan
Log in and navigate to the roster
Select a student
Open the Change Enrollment Modal
Verify that the modal closes properly when the "Cancel" button at the bottom is clicked.

## Automated Testing
- [X] All unit tests are passing.
- [ ] If applicable, unit tests have been added to cover this changeset.

## Additional Context
Wasn't called out in the story, but I did verify that closing with this fix still properly clears the modal of any partially entered data.

### CODE REVIEW

**Review by jessethach — APPROVED** [review]
Looks good!

**Review by bamader — APPROVED** [review]

**Review by JordanGuinn — APPROVED** [review]
@GordonFarrell LGTM, although the build is currently failing?

https://app.circleci.com/pipelines/github/ctoec/data-collection/4287/workflows/96db19c1-4682-4bb1-b64c-254c9ad99ae6/jobs/20379

**Comment by bamader** [comment]
## Validation Plan
- [ ] User can close change enrollment modal with cancel button
- [ ] User can close change enrollment modal with X
- [ ] User can successfully change an enrollment with the modal

**Review by lukenewman — APPROVED** [review]

**Comment by bamader** [comment]
I'm sure this is shocking to us all, but validations are completely clean for this PR, so this is ready to merge!

**Pull request merged**
